services:
  frontend:
    image: "${ECR_CLIENT_URL}:${BRANCH}-${SHA}"
    container_name: frontend_${BRANCH}
    working_dir: /app
    ports:
      - "${FRONTEND_PORT}:80"
    env_file:
      - .env

  backend:
    image: "${ECR_SERVER_URL}:${BRANCH}-${SHA}"
    container_name: backend_${BRANCH}
    working_dir: /run
    ports:
      - "${BACKEND_PORT}:8080"
    env_file:
      - .env
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=ap-southeast-1

  backend2:
    image: "${ECR_SERVER_URL}:${BRANCH}-${SHA}"
    container_name: backend_${BRANCH}_2
    working_dir: /run
    ports:
      - "${BACKEND_PORT_2}:8080"
    env_file:
      - .env
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=ap-southeast-1
