name: CI Phase

on:
  push:
    branches: ["SSMP-31-Implement-CI-CD-pipeline"]
  pull_request:
    branches: ["SSMP-31-Implement-CI-CD-pipeline"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check Docker version
        run: docker --version

      - name: Build server
        env:
          DATASOURCE_URL: ${{ secrets.DATASOURCE_URL }}
          DATASOURCE_USERNAME: ${{ secrets.DATASOURCE_USERNAME }}
          DATASOURCE_PASSWORD: ${{ secrets.DATASOURCE_PASSWORD }}
        run: |
          cd server
          docker build \
            --build-arg DATASOURCE_URL=${{ secrets.DATASOURCE_URL }} \
            --build-arg DATASOURCE_USERNAME=${{ secrets.DATASOURCE_USERNAME }} \
            --build-arg DATASOURCE_PASSWORD=${{ secrets.DATASOURCE_PASSWORD }} \
            -t star_server:${{ github.sha }} .

      - name: Build client
        run: |
          cd client
          docker build -t star_client:${{ github.sha }} .
