name: CI Phase

on:
  push:
    branches: ["SSMP-31-Implement-CI-CD-pipeline"]
  pull_request:
    branches: ["SSMP-31-Implement-CI-CD-pipeline"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: benjlevesque/short-sha@v3.0
        id: short-sha
        with:
          length: 6

      - name: Check Docker version
        run: docker --version

      - name: Build server
        env:
          DATASOURCE_URL: ${{ secrets.DATASOURCE_URL }}
          DATASOURCE_USERNAME: ${{ secrets.DATASOURCE_USERNAME }}
          DATASOURCE_PASSWORD: ${{ secrets.DATASOURCE_PASSWORD }}
          SHA: ${{ steps.short-sha.outputs.sha }}
        run: |
          cd server
          # Make sure Dockerfile is in the `server` directory
          docker build \
            --build-arg DATASOURCE_URL=${{ secrets.DATASOURCE_URL }} \
            --build-arg DATASOURCE_USERNAME=${{ secrets.DATASOURCE_USERNAME }} \
            --build-arg DATASOURCE_PASSWORD=${{ secrets.DATASOURCE_PASSWORD }} \
            -t star_server:${{ env.SHA }} .

      - name: Build client
        env:
          SHA: ${{ steps.short-sha.outputs.sha }}
        run: |
          cd client
          # Make sure Dockerfile is in the `client` directory
          docker build -t star_client:${{ env.SHA }} .
