name: CI Phase Dev

on:
  workflow_call:

jobs:
  build_dev:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ECR_URL: ${{ secrets.ECR_URL }}
      ECR_SERVER_URL: ${{ secrets.ECR_SERVER_URL_DEV }}
      ECR_CLIENT_URL: ${{ secrets.ECR_CLIENT_URL_DEV }}
      DATASOURCE_URL: ${{ secrets.DATASOURCE_URL_DEV }}
      DATASOURCE_USERNAME: ${{ secrets.DATASOURCE_USERNAME }}
      DATASOURCE_PASSWORD: ${{ secrets.DATASOURCE_PASSWORD }}
      VITE_BACKEND_URL: ${{ secrets.VITE_BACKEND_URL_DEV }}
      VITE_BACKEND_AUTH_URL: ${{ secrets.VITE_BACKEND_AUTH_URL_DEV }}
      VITE_REDIRECT_URI: ${{ secrets.VITE_REDIRECT_URI_DEV }}
      VITE_TOKEN_URL: ${{ secrets.VITE_TOKEN_URL_DEV }}
      MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
      AUTH_SERVER_URL: ${{ secrets.AUTH_SERVER_URL_DEV }}
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_DEV }}
      FRONTEND_PORT: ${{ secrets.FRONTEND_PORT_DEV }}
      BACKEND_PORT: ${{ secrets.BACKEND_PORT_DEV }}
      AUTH_PORT: ${{ secrets.AUTH_PORT_DEV }}
      DATABASE_PORT: ${{ secrets.DATABASE_PORT_DEV }}


    steps:
      - uses: actions/checkout@v4

      - uses: benjlevesque/short-sha@v3.0
        id: short-sha
        with:
          length: 6

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Check Docker version
        run: docker --version

        # Pre-build Client
      - name: Pre-build Client
        run: |
          cd client
          envsubst < .env > .env.tmp && mv .env.tmp .env
          cat .env

      - name: Pre-build Server
        run: |
          cd server/src/main/resources
          envsubst < application.properties > application.properties.tmp && mv application.properties.tmp application.properties
          cat application.properties

      - name: Build server
        env:
          SHA: ${{ steps.short-sha.outputs.sha }}
          BRANCH: ${{ steps.extract_branch.outputs.branch }}
        run: |
          cd server
          docker build -t star_server:"${{ env.BRANCH }}-${{ env.SHA }}" .
          docker tag star_server:"${{ env.BRANCH }}-${{ env.SHA }}" "${{ env.ECR_SERVER_URL }}":"${{ env.BRANCH }}-${{ env.SHA }}"
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ env.ECR_URL }}
          docker push "${{ env.ECR_SERVER_URL }}:${{ env.BRANCH }}-${{ env.SHA }}"
        continue-on-error: false

      - name: Build client
        env:
          SHA: ${{ steps.short-sha.outputs.sha }}
          BRANCH: ${{ steps.extract_branch.outputs.branch }}
        run: |
          cd client
          docker build -t star_client:"${{ env.BRANCH }}-${{ env.SHA }}" .
          docker tag star_client:"${{ env.BRANCH }}-${{ env.SHA }}" "${{ env.ECR_CLIENT_URL }}":"${{ env.BRANCH }}-${{ env.SHA }}"
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ env.ECR_URL }}
          docker push "${{ env.ECR_CLIENT_URL }}:${{ env.BRANCH }}-${{ env.SHA }}"
        continue-on-error: false

      - name: Build artifact
        env:
          SHA: ${{ steps.short-sha.outputs.sha }}
          BRANCH: ${{ steps.extract_branch.outputs.branch }}
        run: |
          touch .env
          echo "ECR_CLIENT_URL=${{ env.ECR_CLIENT_URL }}" >> .env
          echo "ECR_SERVER_URL=${{ env.ECR_SERVER_URL }}" >> .env
          echo "BRANCH=${{ env.BRANCH }}" >> .env
          echo "SHA=${{ env.SHA }}" >> .env
          echo "FRONTEND_PORT=${{ env.FRONTEND_PORT }}" >> .env
          echo "BACKEND_PORT=${{ env.BACKEND_PORT }}" >> .env
          echo "AUTH_PORT=${{ env.AUTH_PORT }}" >> .env
          echo "DATABASE_PORT=${{ env.DATABASE_PORT }}" >> .env
        continue-on-error: false

      - uses: hkusu/s3-upload-action@v2
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: "ap-northeast-1"
          aws-bucket: ${{ env.AWS_S3_BUCKET }}
          file-path: ".env"
          destination-dir: "/"
          bucket-root: "/"

      - uses: hkusu/s3-upload-action@v2
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: "ap-northeast-1"
          aws-bucket: ${{ env.AWS_S3_BUCKET }}
          file-path: "docker-compose.yml"
          destination-dir: "/"
          bucket-root: "/"
