name: CI Phase

on:
  push:
    branches: ["SSMP-31-Implement-CI-CD-pipeline", "main", "develop"]
  pull_request:
    branches: ["SSMP-31-Implement-CI-CD-pipeline", "main", "develop"]

jobs:
  build:
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: benjlevesque/short-sha@v3.0
        id: short-sha
        with:
          length: 6

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Check Docker version
        run: docker --version

      - name: Build server
        env:
          DATASOURCE_URL: ${{ secrets.DATASOURCE_URL }}
          DATASOURCE_USERNAME: ${{ secrets.DATASOURCE_USERNAME }}
          DATASOURCE_PASSWORD: ${{ secrets.DATASOURCE_PASSWORD }}
          ECR_SERVER_URL: ${{ secrets.ECR_SERVER_URL }}
          ECR_CLIENT_URL: ${{ secrets.ECR_CLIENT_URL }}
          SHA: ${{ steps.short-sha.outputs.sha }}
          BRANCH: ${{ steps.extract_branch.outputs.branch }}
        run: |
          cd server
          docker build --build-arg DATASOURCE_URL="${{ env.DATASOURCE_URL }}" --build-arg DATASOURCE_USERNAME="${{ env.DATASOURCE_USERNAME }}" --build-arg DATASOURCE_PASSWORD="${{ env.DATASOURCE_PASSWORD }}" -t star_server:"${{ env.BRANCH }}-${{ env.SHA }}" .
          docker tag star_server:"${{ env.BRANCH }}-${{ env.SHA }}" "${{ env.ECR_SERVER_URL }}":"${{ env.BRANCH }}-${{ env.SHA }}"

      - name: Push Server Image to ECR
        uses: jwalton/gh-ecr-push@v2
        env:
          SHA: ${{ steps.short-sha.outputs.sha }}
          BRANCH: ${{ steps.extract_branch.outputs.branch }}
          ECR_SERVER_URL: ${{ secrets.ECR_SERVER_URL }}
          ECR_CLIENT_URL: ${{ secrets.ECR_CLIENT_URL }}
        with:
          access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          region: ap-southeast-1
          image: "${{ env.ECR_SERVER_URL }}:${{ env.BRANCH }}-${{ env.SHA }}"

      - name: Build client
        run: |
          cd client
          docker build -t star_client:"${{ env.BRANCH }}-${{ env.SHA }}" .
          docker tag star_client:"${{ env.BRANCH }}-${{ env.SHA }}" "${{ env.ECR_CLIENT_URL }}":"${{ env.BRANCH }}-${{ env.SHA }}"

      - name: Push Client Image to ECR
        uses: jwalton/gh-ecr-push@v2
        env:
          SHA: ${{ steps.short-sha.outputs.sha }}
          BRANCH: ${{ steps.extract_branch.outputs.branch }}
          ECR_SERVER_URL: ${{ secrets.ECR_SERVER_URL }}
          ECR_CLIENT_URL: ${{ secrets.ECR_CLIENT_URL }}
        with:
          access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          region: ap-southeast-1
          image: "${{ env.ECR_CLIENT_URL }}:${{ env.BRANCH }}-${{ env.SHA }}"
