name: Build and Snyk Security

on:
    workflow_call:

jobs:
  test-build:
    env:
      DATASOURCE_URL: ${{ secrets.DATASOURCE_URL }}
      DATASOURCE_USERNAME: ${{ secrets.DATASOURCE_USERNAME }}
      DATASOURCE_PASSWORD: ${{ secrets.DATASOURCE_PASSWORD }}
      VITE_BASE_URL: ${{ secrets.VITE_BASE_URL }}
      VITE_BACKEND_URL: ${{ secrets.VITE_BACKEND_URL }}
      VITE_BACKEND_AUTH_URL: ${{ secrets.VITE_BACKEND_AUTH_URL }}
      VITE_CLIENT_ID: ${{ secrets.VITE_CLIENT_ID }}
      VITE_REDIRECT_URI: ${{ secrets.VITE_REDIRECT_URI }}
      VITE_TOKEN_URL: ${{ secrets.VITE_TOKEN_URL }}
      VITE_CLIENT_SECRET: ${{ secrets.VITE_CLIENT_SECRET }}

    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v4

        # Pre-build Client
        - name: Pre-build Client
          run: |
            cd client
            touch .env
            echo "VITE_BASE_URL=${{ env.VITE_BASE_URL }}" >> .env
            echo "VITE_BACKEND_URL=${{ env.VITE_BACKEND_URL }}" >> .env
            echo "VITE_BACKEND_AUTH_URL=${{ env.VITE_BACKEND_AUTH_URL }}" >> .env
            echo "VITE_CLIENT_ID=${{ env.VITE_CLIENT_ID }}" >> .env
            echo "VITE_REDIRECT_URI=${{ env.VITE_REDIRECT_URI }}" >> .env
            echo "VITE_TOKEN_URL=${{ env.VITE_TOKEN_URL }}" >> .env
            echo "VITE_CLIENT_SECRET=${{ env.VITE_CLIENT_SECRET }}" >> .env
            npm install
            npm run build
          continue-on-error: false

        # Pre-build Server
        - name: Pre-build Server
          uses: actions/setup-java@v3
          with:
            distribution: "temurin"
            java-version: "21"

        - name: Build Server
          run: |
            cd server/src/main/resources
            echo "DATASOURCE_URL=${{ env.DATASOURCE_URL }}" >> application.properties
            echo "DATASOURCE_USERNAME=${{ env.DATASOURCE_USERNAME }}" >> application.properties
            echo "DATASOURCE_PASSWORD=${{ env.DATASOURCE_PASSWORD }}" >> application.properties
            cd ../../..
            chmod +x gradlew
            ./gradlew build
          continue-on-error: false
