name: Snyk Security

on:
  push:
    branches: ["SSMP-31-Implement-CI-CD-pipeline"]
  # pull_request:
  #   branches: ["main"]

permissions:
  contents: read

jobs:
  snyk:
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Set up Snyk CLI to check for security issues
      - name: Set up Snyk CLI
        uses: snyk/actions/setup@806182742461562b67788a64410098c9d9b96adb

      # Install Java dependencies using Gradle
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Build with Gradle
        run: |
          cd server
          chmod +x gradlew
          ./gradlew build

      # Snyk test for Java (server) and save SARIF report
      - name: Snyk test for Java
        run: |
          echo $SNYK_TOKEN
          cd server
          snyk test --all-projects --sarif-file-output=snyk-java.sarif || true

      # Install Node.js dependencies for React (client)
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Node.js dependencies
        run: |
          cd client
          npm install

      # Snyk test for React (client) and save SARIF report
      - name: Snyk test for React
        run: |
          cd client
          snyk test --sarif-file-output=snyk-react.sarif || true

      # Merge SARIF files and upload the result to GitHub Code Scanning
      - name: Merge SARIF files and upload
        run: jq -s '.[0] * .[1]' server/snyk-java.sarif client/snyk-react.sarif > snyk-combined.sarif
      - name: Upload combined SARIF to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-combined.sarif
